## This deployment runs a single ubuntu container with a sleep command in a loop the default namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-sleep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-sleep
  template:
    metadata:
      labels:
        app: ubuntu-sleep
    spec:
      containers:
      - name: ubuntu-sleep
        image: ubuntu
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
